### PR TITLE
Use lodash-es instead of lodash

### PR DESCRIPTION
**Pull request by atfzl**
Created over base branch https://github.com/casesandberg/react-color/pull/721, reduces 70KB total bundle size. 

Resolves https://github.com/casesandberg/react-color/issues/687 a little

### CODE REVIEW

**Comment by atfzls** [comment]
Right now tests are failing because `.babelrc` contains modules: false. I'll try to find solution for this.

I need to figure out how to have 2 babel configs, one for test and `commonjs` code emit, second for es module code emit.

**Comment by anuraghazra** [comment]
@atfzl any luck with this?

**Comment by atfzls** [comment]
@anuraghazra Will work on this in first week of July

**Comment by anuraghazra** [comment]
Can we just use the standalone packages of lodash.merge, throttle, etc instead of changing the babel stuff. It would be easier I think, it won't break the build.

**Comment by atfzls** [comment]
@anuraghazra I tried using standalone packages of the functions, but there are many functions (around 6-7) because of which there isn't a lot of decrease in size. Each package is big because they are not sharing any code between themselves.

**Comment by atfzl** [comment]
Don't know why tests are failing, they are working on my setup after the latest commits.

**Comment by atfzl** [comment]
Was able to reproduce the test errore at the exact node and npm version

**Comment by atfzl** [comment]
@casesandberg Please have a look at this, the tests are passing now.

**Comment by casesandberg** [comment]
This looks good to me! Congrats on your first-time contribution 🎉  I am going to be adding you as a collaborator, feel free to accept if you are interested in helping with the project!

**Pull request merged**
