### PR TITLE
Updated doc examples to allow clicks within picker control

### PR DESCRIPTION
**Pull request by jeremyadavis**
Added wrapper to doc examples to let users click within the color picker control to edit things like the hex values directly.

Updated package.json to get around unmet peer dependencies

### CODE REVIEW

**Comment by casesandberg** [comment]
I am not sure why this is necessary, can you explain?

**Comment by jeremyadavis** [comment]
In the docs under [More Examples](http://casesandberg.github.io/react-color/#examples) the popup color pickers won't allow hex values to be edited. The cover is taking the click and closing the control.

At least on Chrome it was.

**Comment by casesandberg** [comment]
Can you drop the `package.json` changes and fix the merge conflicts in this and then I can merge!

**Comment by casesandberg** [comment]
Going to close, feel free to reopen when you update!

**Pull request closed without merging**
