### PR TITLE
Add styles prop to all components

### PR DESCRIPTION
**Pull request by alampros**
Merge passed-in styles into reactCSS config for all components to allow for customizing styles.
Add tests.

Would be happy to add to the docs for this, but #446 is in my way.

### CODE REVIEW

**Comment by flyandi** [comment]
Could we promote this please - this would give us a lot of flexibility in terms of custom styling.

**Comment by Theoton** [comment]
I think a lot of people need this, like me.

**Comment by BofEmptiness** [comment]
When i can use it? :) @alampros

**Comment by BofEmptiness** [comment]
I think this project is dead, so i just edit it in sourse :/

**Comment by alampros** [comment]
It would pretty awesome to rebuild this with [emotion](https://emotion.sh/) and a `<ThemeProvider>`...

**Comment by alampros** [comment]
The tests still pass and the storybook works, so I'm going to merge this.

**Comment by alampros** [comment]
@casesandberg will have to publish a new version to npm, but for now you can use the repo shorthand in your package.json to get the master.

Cheers! 🍻

**Comment by Theoton** [comment]
> @casesandberg will have to publish a new version to npm, but for now you can use the repo shorthand in your package.json to get the master.
> 
> Cheers! 🍻

That's good news. Waitting...

**Comment by casesandberg** [comment]
Apologies for the delay. This has been published at `react-color@2.17.0`

**Comment by sachdeva-shrey** [comment]
Hi! I've been trying this but I'm kinda stuck. Can you please add an example or document this somewhere? @alampros @casesandberg

**Pull request merged**
