### PR TITLE
Remove React and React DOM Peer Dependencies

### PR DESCRIPTION
**Pull request by casesandberg**
This fixes https://github.com/casesandberg/react-color/issues/264#issuecomment-261564652. I think this is a good call @sarahzinger !!

### CODE REVIEW

**Comment by sarahzinger** [comment]
I know this was my original suggestion but I'm still getting the error unfortunately. For a short term fix we are matching our version of react to be the same as yours again. I think our long term strategy right now for this is going to be seeing if we can move towards npm3 since we wanted to do it anyway. Sorry for the sloppy prs this morning without a lot of detail, was just trying to find a fix as fast as possible. If we figure out what the actual problem is, will be sure to let you know thanks for all of your help!

**Comment by AviVahl** [comment]
peerDeps is a fiasco on npm2.

@casesandberg  If you want to support npm2 and be as react-version-agnostic as possible:
- Remove peerDeps of reactcss:
https://github.com/casesandberg/reactcss/blob/master/package.json#L73
- Publish a new reactcss version and use it in react-color.
- Move react-addons-shallow-compare from dep to devDep:
https://github.com/casesandberg/react-color/blob/master/package.json#L43

react-addons-shallow-compare would then also be an implicit dep for anyone using react-color.

In npm3-land, you would simply put react, react-dom, and react-addons-shallow-compare in peerDeps

Hope this helps.

**Comment by casesandberg** [comment]
Thanks @AviVahl, I think that makes a lot of sense to go that route. Going to be doing that this morning: https://github.com/casesandberg/react-color/issues/296

**Comment by casesandberg** [comment]
@sarahzinger I just released `react-color@2.6.0` which should fix your problems :)

**Comment by sarahzinger** [comment]
I just tried 2.6.0 but it still installs its own version of react :( so
strange.

**Comment by AviVahl** [comment]
@sarahzinger I just tested it on my end with npm2:
```
C:\projects\react-color-test
λ npm -v
2.15.11

C:\projects\react-color-test
λ npm init -f
npm WARN using --force I sure hope you know what you are doing.
Wrote to C:\projects\react-color-test\package.json:

{
  "name": "react-color-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

C:\projects\react-color-test  (react-color-test@1.0.0)
λ npm i react@15.3.1 react-dom@15.3.1 react-color --save
npm WARN package.json react-color-test@1.0.0 No description
npm WARN package.json react-color-test@1.0.0 No repository field.
npm WARN package.json react-color-test@1.0.0 No README data
react-dom@15.3.1 node_modules\react-dom

react-color@2.8.0 node_modules\react-color
├── material-colors@1.2.0
├── tinycolor2@1.4.1
├── reactcss@1.1.1 (object-assign@4.1.0, merge@1.2.0, classnames@2.2.5)
└── lodash@4.17.2

react@15.3.1 node_modules\react
├── object-assign@4.1.0
├── loose-envify@1.3.0 (js-tokens@2.0.0)
└── fbjs@0.8.6 (ua-parser-js@0.7.12, promise@7.1.1, isomorphic-fetch@2.2.1, core-js@1.2.7)

C:\projects\react-color-test  (react-color-test@1.0.0)
λ npm ls react
react-color-test@1.0.0 C:\projects\react-color-test
└── react@15.3.1
```
Only a single version of React is installed. I tested it further by removing the carets from package.json, deleting node_modules, and running `npm i`. Still a single react (of an older version).
Please note that it did install the latest react-color (2.**8**.0), so maybe that's the difference.

**Comment by sarahzinger** [comment]
@AviVahl thanks that 2.8.0 did the trick!

**Pull request merged**
