### PR TITLE
Allow Github.js receive width props as percentage

### PR DESCRIPTION
**Pull request by Gtosta96**
I am receiving warnings about width props just allow numbers, but I want to pass it as percentage ('100%')...
Actually, the behavior works as expected, but the warnings is sucks.

### CODE REVIEW

**Comment by yadomi** [comment]
This is great, maybe this should be added on other pickers where `width` can be provided as well ? (eg: `Block.js`, `Circle.js`, `Sketch.js`, `Swatches.js` and `Twitter.js`)

cc @casesandberg

**Comment by casesandberg** [comment]
Ah, that was my bad for switching it. This PR looks great, @Gtosta96 would you mind pushing up a commit with the rest of the components that have width props? https://github.com/casesandberg/react-color/search?utf8=%E2%9C%93&q=width%3A+PropTypes.number&type=

**Comment by Gtosta96** [comment]
Hello, Thanks for feedback,
I'm working on other pickers and gotta send another PR!

**Comment by Gtosta96** [comment]
Hey @casesandberg I've just sent the updates!
Hope it helps!

**Comment by casesandberg** [comment]
This is fantastic, thanks!

**Comment by casesandberg** [comment]
Thanks a lot for contributing to React Color! I've invited you to join the repo as a contributor – no pressure to accept! Feel free to reach out with any questions.

**Pull request merged**
