### PR TITLE
use react 15.0.1

### PR DESCRIPTION
**Pull request by jaeh**
update css positional values from 0 to 0px,
for bottom, left, right, top and Absolute values.

### CODE REVIEW

**Comment by jaeh** [comment]
wrote some more on
https://github.com/casesandberg/react-color/issues/114#issuecomment-211110982
about the tests failing

**Comment by Kerumen** [comment]
Why not `top: 0,` instead of `top: '0px',`? It's more concise and there is no need to specify the `px` unit because it's implicitly set when written in number format.

**Comment by jaeh** [comment]
all of the code uses strings so far, i did not want to break that pattern.

@casesandberg if you would prefer numbers instead of strings i can update my pr

**Comment by joshdover** [comment]
@Kerumen This feature is being deprecated by React in the future: https://facebook.github.io/react/blog/2016/04/07/react-v15.html#new-helpful-warnings and facebook/react#5140

**Comment by Kerumen** [comment]
@joshdover `top: '0'` is deprecated (notice the _string_ value) but `top: 0` is not (notice the _number_ value). [Unitless number values like width: 300 are unchanged.](https://facebook.github.io/react/blog/2016/04/07/react-v15.html#new-helpful-warnings)

**Comment by joshdover** [comment]
@Kerumen ah not sure how I missed that 👍

**Comment by daiheitan** [comment]
Is anyone still working on this PR? I'm waiting for this to be landed..

**Comment by joshdover** [comment]
Maintainer hasn't had any github activity since April 1st 😦

**Comment by joshdover** [comment]
@casesandberg Why was this closed? #126 doesn't fix the issue that this resolves, which is all the deprecation warnings on.

**Pull request closed without merging**
