### PR TITLE
408 - bugfix - check percentages in color validation

### PR DESCRIPTION
**Pull request by kyrasteen**
Thought I would offer a fix for issue #408 even though the 'help wanted' tag is not on it. All tests still passing.

### CODE REVIEW

**Comment by casesandberg** [comment]
This is awesome, thank you! Do you mind writing a simple test to cover the changes?

**Comment by kyrasteen** [comment]
Sure thing. I will add a test for my changes.

**Comment by casesandberg** [comment]
Thanks for the first contribution! I've invited you to join the repo as a collaborator – no pressure to accept! Feel free to reach out with any questions.

**Comment by casesandberg** [comment]
This is live in `react-color@2.14.0` 🎉

**Pull request merged**
