### PR TITLE
add missing bottom-right type

### PR DESCRIPTION
**Pull request by scttcper**

### CODE REVIEW

**Comment by ddelrio1986** [comment]
Why not bottom-left too?

**Comment by scttcper** [comment]
css already exists for bottom-right but not bottom-left

**Comment by casesandberg** [comment]
Thanks!

I just added an issue to track adding bottom-left in the future https://github.com/casesandberg/react-color/issues/429

**Comment by casesandberg** [comment]
This is live in `react-color@2.14.0` 🎉

**Pull request merged**
