### PR TITLE
align to react 0.14.x

### PR DESCRIPTION
**Pull request by u9520107**
Removed findDOMNode usages.
Also change React.render to ReactDOM.render in docs.

#42

### CODE REVIEW

**Comment by b2whats** [comment]
+1

**Comment by conorhastings** [comment]
@u9520107 can you resolve conflicts?

**Comment by conorhastings** [comment]
@casesandberg anyway you can get this merged? relying on react color in a project that we want to bump up to 0.14

**Comment by casesandberg** [comment]
Merged in here: https://github.com/casesandberg/react-color/pull/47

**Pull request closed without merging**
