### PR TITLE
Directory caps

### LINKED ISSUE #23: Cannot find module './sketch/Sketch'
When building my component using browserify it fails to resolve the `sketch/Sketch` module. 

The problem seems to be this lowercase path:

```js
var Sketch = require('./sketch/Sketch');
```
https://github.com/casesandberg/react-color/blob/master/src/components/Color.jsx#L10

in `src/components` there are two sketch folders. One lowercase and the other one is uppercase. In `lib/components` there is only the uppercase folder.

Changing the require statement from above to uppercase...

```js
var Sketch = require('./Sketch/Sketch');
```
... fixes the problem.

### PR DESCRIPTION
**Pull request by rickyvetter**
Fixes #23 -this error is caused by a known difference between [linux and mac filesystems and case sensitivity](http://apple.stackexchange.com/questions/22297/is-bash-in-osx-case-insensitive). Also, I ran `gulp prod`, if there are other steps you want for PRs, let me know!

### CODE REVIEW

**Comment by grassick** [comment]
I'm using a fork because of this one (thanks @rickyvetter). The PR works great on my system at least.

**Comment by JedWatson** [comment]
Sorry to bump, but we just integrated react-color into [Keystone JS](https://github.com/keystonejs/keystone) and this is causing our build to fail for several users. So landing this PR would be really appreciated!

**Comment by JedWatson** [comment]
@casesandberg please merge? this is a real show stopper for us. I'd prefer not to fork over it.

**Comment by rickyvetter** [comment]
@JedWatson we had to fork since we are using this in prod. feel free to use https://github.com/socialtables/react-color (@socialtables/react-color on npm) until this gets applied.

**Comment by jonathanong** [comment]
+1

**Comment by asaldivar** [comment]
+1

**Comment by jonathanong** [comment]
@rickyvetter can you publish it as public?

**Comment by JedWatson** [comment]
@jonathanong I've published mine as public; you can use `"@jedwatson/react-color": "^1.0.6",`

**Comment by rickyvetter** [comment]
@jonathanong apparently npm only allows publishing namespaced modules as public on initial publish. Thanks @jedwatson for getting something public out there :)

**Comment by jonathanong** [comment]
Thanks!!!

**Comment by iam4x** [comment]
You can also do: `npm i -S rickyvetter/react-color#directory-caps` it will use code from github.

Thank's for the fix, I need this too :+1:

**Pull request merged**
