### PR TITLE
Correct path for components in documentation

### PR DESCRIPTION
**Pull request by simonlovesyou**

### CODE REVIEW

**Comment by casesandberg** [comment]
Oh, thank you!

Can you run `npm run docs-dist` and commit that up so the documentation site will be updated?

**Comment by simonlovesyou** [comment]
Sure!

**Comment by casesandberg** [comment]
Sorry, one last time:

Can you run `npm install` and then `npm run docs-dist`, there are too many changes in the docks bundle which leads me to believe you didnt have all of the packages installed.

**Comment by simonlovesyou** [comment]
Welp, that's what I did. I must have a different version to yours of `webpack` due to the versioning flag in `package.json`. 

I `rm -rf node_modules/` and tried it again nonetheless, but I get the same output as before.

**Comment by casesandberg** [comment]
Thanks for your help, I got this merged in with `react-color@2.4.3`

**Pull request closed without merging**
