### PR TITLE
Removed console.log()

### PR DESCRIPTION
**Pull request by CremAlex**
Removed console.log()

### CODE REVIEW

**Comment by casesandberg** [comment]
Oh man, good catch! Can you run `npm run lib` and commit that as well?

**Comment by CremAlex** [comment]
Done :-)

**Comment by isTravis** [comment]
Thanks for this PR and for merging it. I'm still seeing this though on v2.2.0 which is the latest on npm. 

Any chance to push the updated code to a new npm version?

**Comment by CremAlex** [comment]
Well yes it seems on this merge the log came back 
https://github.com/casesandberg/react-color/commit/f29c918290e9c63851176fcd3288bbb5e767219f#diff-05beea2169d9a4fc0b781db8e7ceceb9R20391

**Pull request merged**
