### PR TITLE
Fonts should be served over HTTPS

### PR DESCRIPTION
**Pull request by louh**
Your site is being loaded over HTTPS now, so fonts are not loaded because it is loaded on HTTP. In Chrome (v52) the console error message is "Mixed Content: The page at 'https://casesandberg.github.io/react-color/#usage-include' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Roboto:500,300,400'. This request has been blocked; the content must be served over HTTPS."

There is no reason not to load external files over HTTPS if they support it!

Thanks for the excellent library!

### CODE REVIEW

**Comment by casesandberg** [comment]
Oh perfect! Can you run `npm run docs-dist` and push it up as well? Then I can get this merged

**Comment by louh** [comment]
Sure - done!

**Comment by louh** [comment]
@casesandberg I just noticed that I had done this wrong and you had to publish a fix. Do you know what I might be missing?

**Comment by casesandberg** [comment]
Ah! It was a problem with you not having a specific package locally I think. I need to add an npm install to the predocs-dist to make sure all of the right packages are installed :)

**Pull request merged**
